//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonMetadata.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1B9Q0Y02W3RCF0ZKQ9R2")]
        public string AmazonSubscriptionId {
            get {
                return ((string)(this["AmazonSubscriptionId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")]
        public string AmazonMetadata_com_amazon_webservices_AWSECommerceService {
            get {
                return ((string)(this["AmazonMetadata_com_amazon_webservices_AWSECommerceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DVD")]
        public string AmazonSearchMode {
            get {
                return ((string)(this["AmazonSearchMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.com/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlEN {
            get {
                return ((string)(this["AmazonUrlEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.co.uk/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlUK {
            get {
                return ((string)(this["AmazonUrlUK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.de/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlDE {
            get {
                return ((string)(this["AmazonUrlDE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.co.jp/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlJP {
            get {
                return ((string)(this["AmazonUrlJP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.fr/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlFR {
            get {
                return ((string)(this["AmazonUrlFR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://soap.amazon.ca/onca/soap?Service=AWSECommerceService")]
        public string AmazonUrlCA {
            get {
                return ((string)(this["AmazonUrlCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Action</string>
  <string>Adventure</string>
  <string>Animated</string>
  <string>Animation</string>
  <string>Biography</string>
  <string>Comedy</string>
  <string>Crime</string>
  <string>Documentary</string>
  <string>Drama</string>
  <string>Family</string>
  <string>Fantasy</string>
  <string>Film-Noir</string>
  <string>Game-Show</string>
  <string>History</string>
  <string>Horror</string>
  <string>Music</string>
  <string>Musical</string>
  <string>Mystery</string>
  <string>News</string>
  <string>Reality-TV</string>
  <string>Romance</string>
  <string>Sci-Fi</string>
  <string>Short</string>
  <string>Sport</string>
  <string>Talk-Show</string>
  <string>Thriller</string>
  <string>War</string>
  <string>Western</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Genres {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Genres"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("US")]
        public string AmazonLocale {
            get {
                return ((string)(this["AmazonLocale"]));
            }
            set {
                this["AmazonLocale"] = value;
            }
        }
    }
}
